language: node_js

jobs:
  include:
    - name: 'node:latest'
      node_js: 'node'
      after_success: npm run coveralls
    - name: 'node:lts'
      node_js: 'lts/*'

notifications:
  email: false
