language: node_js
os: linux
node_js: 'lts/*'

addons:
  apt:
    packages:
      - libgconf-2-4

stages:
  - name: test
  - name: deploy
    if: (tag =~ ^v)

jobs:
  include:
    - name: 'node:lts'
      stage: test
      script:
        - yarn cypress install
        - yarn build
        - yarn demo:build
        - yarn coverage
        - yarn cypress:run
    - name: 'demo'
      stage: deploy
      script:
        - yarn demo:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: './dist/demo'
        on:
          tags: true
    - name: 'npm'
      stage: deploy
      script:
        - yarn build
      deploy:
        provider: npm
        cleanup: false
        email: $NPM_EMAIL
        api_token: $NPM_APIKEY
        edge: true
        on:
          tags: true

notifications:
  email: false
