language: node_js

node_js: 'node'

jobs:
  include:
    - name: 'node:lts'
      node_js: 'lts/*'
    - name: 'node:latest'
      script:
        - npm test
        - npm run demo:build
      after_success:
        - npm run coveralls
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: './demo'
        on:
          branch: master

notifications:
  email: false
