language: node_js

node_js: 'lts/*'

cache:
  directories:
    - ~/.npm

stages:
  - name: test
  - name: deploy
    if: (tag =~ ^v)

jobs:
  include:
    - name: 'node:lts'
      stage: test
      script:
        - npm run build
        - npm run demo:build
        - npm run coverage
        - npm run cypress:run
    - name: 'node:latest'
      node_js: 'node'
      stage: test
    - name: 'demo'
      stage: deploy
      script:
        - npm run demo:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: './dist/demo'
        on:
          tags: true
    - name: 'npm'
      stage: deploy
      script:
        - npm run build
      deploy:
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_APIKEY
        on:
          tags: true

notifications:
  email: false
